server:
  port: ${api.port.notification-service}
  error:
    include-message: always
    include-binding-errors: always
spring:
  config:
    import: configserver:http://${CONFIG_SERVER_HOSTNAME:localhost}:${CONFIG_SERVER_PORT:9999}
  rabbitmq:
    host: ${RABBITMQ_HOSTNAME:localhost}
    port: ${RABBITMQ_PORT:5672}
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 10
        max-interval: 5000
        multiplier: 1.5
  mail:
    host: ${MAILDEV_HOSTNAME:localhost}
    port: ${MAILDEV_PORT:1025}
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
